apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring
    tier: frontend
  clusterIP: 10.100.113.23
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring
        tier: frontend
    spec:
      containers:
      - image: mawfia/swe645a4-spring:1.0
        name: spring
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 8080
          name: spring
